name: Deploy Dev Build

on:
  push:
    branches: [ "ubuntu-dev-release" ]
  pull_request:
    branches: [ "ubuntu-dev-release" ]

jobs:
  Deploy-Dev-Build:
    runs-on: self-hosted
    steps:
      - run: cd ~/dev/back && git reset --hard
      - run: systemctl --user stop api.service
      - run: cd ~/dev/back/ && git pull origin --force ubuntu-dev-release
      - run: cd ~/dev/back/Publish && chmod +x SpectruMineAPI
      - run: systemctl --user start api.service
